name: Deploy to npm

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ '10.x' }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - name: Lint
        run: npm run lint
      - name: Check Formating
        run: npm run check-format
      - name: Build
        run: npm run build
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
